openapi: 3.2.0
info:
  contact:
    email: federico.giuntoli@flowpay.it
    name: Federico Giuntoli
  description: Hai uno use case di pagamento complesso come pagamenti massivi, split o pagopa?
  termsOfService: https://www.flowpay.it/tos
  title: FlowPay Saldo API
  version: 1.0.0
servers:
- url: https://app.flowpay.it/api
  variables: {}
tags:
- description: 'Saldo conto corrente


    ## Balance Type

    The balance types given by this endpoint can be any of the following:


    | name | description |

    |---|---|

    | expected | Balance composed of booked entries and pending items known at the time of calculation, which projects the end of day balance if everything is booked on the account and no other entry is posted.'
  name: Saldo
paths:
  /{tenantID}/balances:
    get:
      description: Ottiene la lista di tutti i punti saldo per ogni IBAN dell'azienda
      parameters:
      - description: ID dell'owner della richiesta
        example: 84461172-4326-4D6B-AEA7-840ED1372200
        in: path
        name: tenantID
        required: true
        schema:
          example: 84461172-4326-4D6B-AEA7-840ED1372200
          format: uuid
          type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              example:
                IT27H0300203280878355659528:
                  EUR:
                    available:
                      balance: 123.45
                      balanceType: interimAvailable
                      currency: EUR
                      date: 742596848.647101
                      iban: IT27H0300203280878355659528
                IT59Q0300203280162876621571:
                  EUR:
                    closingBooked:
                      balance: 54.32
                      balanceType: closingBooked
                      currency: EUR
                      date: 742596848.647087
                      iban: IT59Q0300203280162876621571
                    interimAvailable:
                      balance: 100
                      balanceType: interimAvailable
                      currency: EUR
                      date: 742596848.647084
                      iban: IT59Q0300203280162876621571
              schema:
                $ref: '#/components/schemas/Balances'
          description: ''
        '400':
          content:
            application/json; charset=utf-8:
              example:
                code: 12345678
                errorDescription: hello
                errorURI: null
                expectedType: null
                field: null
                requestID: null
                service: 12345678
                statusCode: 12345678
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: La richiesta non è corretta sintatticamente, body, headers, path o query params non conformi alla documentazione
        '401':
          content:
            application/json; charset=utf-8:
              example:
                code: 12345678
                errorDescription: hello
                errorURI: null
                expectedType: null
                field: null
                requestID: null
                service: 12345678
                statusCode: 12345678
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Le credenziali fornite non sono sufficienti a completare la richiesta
        '403':
          content:
            application/json; charset=utf-8:
              example:
                code: 12345678
                errorDescription: hello
                errorURI: null
                expectedType: null
                field: null
                requestID: null
                service: 12345678
                statusCode: 12345678
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: La richiesta non è autorizzata a procedere con le credenziali fornite
        '404':
          content:
            application/json; charset=utf-8:
              example:
                code: 12345678
                errorDescription: hello
                errorURI: null
                expectedType: null
                field: null
                requestID: null
                service: 12345678
                statusCode: 12345678
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: La richiesta fa riferimento ad una risorsa inesistente
        '417':
          content:
            application/json; charset=utf-8:
              example:
                code: 12345678
                errorDescription: hello
                errorURI: null
                expectedType: null
                field: null
                requestID: null
                service: 12345678
                statusCode: 12345678
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: La richiesta non è corretta semanticamente
      security:
      - ThirdPartyClientCredential:
        - account:read
      - ThirdPartyAuthorizationCode:
        - account:read
      summary: Lista
      tags:
      - Saldo
      operationId: getByTenantIDBalances
      x-operation-id-source: derived
  /{tenantID}/balances/last:
    get:
      description: Ottiene il saldo più recente per ogni IBAN dell'azienda
      parameters:
      - description: ID dell'owner della richiesta
        example: 84461172-4326-4D6B-AEA7-840ED1372200
        in: path
        name: tenantID
        required: true
        schema:
          example: 84461172-4326-4D6B-AEA7-840ED1372200
          format: uuid
          type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              example:
                IT27H0300203280878355659528:
                  EUR:
                    available:
                      balance: 453
                      balanceType: interimAvailable
                      currency: EUR
                      date: 742596848.647101
                      iban: IT27H0300203280878355659528
                IT59Q0300203280162876621571:
                  EUR:
                    closingBooked:
                      balance: 98
                      balanceType: closingBooked
                      currency: EUR
                      date: 742596848.647087
                      iban: IT59Q0300203280162876621571
                    interimAvailable:
                      balance: 100
                      balanceType: interimAvailable
                      currency: EUR
                      date: 742596848.647084
                      iban: IT59Q0300203280162876621571
                  GBP:
                    closingBooked:
                      balance: 882
                      balanceType: closingBooked
                      currency: GBP
                      date: 742596848.647093
                      iban: IT59Q0300203280162876621571
                    interimAvailable:
                      balance: 649
                      balanceType: interimAvailable
                      currency: GBP
                      date: 742596848.647092
                      iban: IT59Q0300203280162876621571
              schema:
                $ref: '#/components/schemas/LatestBalances'
          description: ''
        '400':
          content:
            application/json; charset=utf-8:
              example:
                code: 12345678
                errorDescription: hello
                errorURI: null
                expectedType: null
                field: null
                requestID: null
                service: 12345678
                statusCode: 12345678
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: La richiesta non è corretta sintatticamente, body, headers, path o query params non conformi alla documentazione
        '401':
          content:
            application/json; charset=utf-8:
              example:
                code: 12345678
                errorDescription: hello
                errorURI: null
                expectedType: null
                field: null
                requestID: null
                service: 12345678
                statusCode: 12345678
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Le credenziali fornite non sono sufficienti a completare la richiesta
        '403':
          content:
            application/json; charset=utf-8:
              example:
                code: 12345678
                errorDescription: hello
                errorURI: null
                expectedType: null
                field: null
                requestID: null
                service: 12345678
                statusCode: 12345678
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: La richiesta non è autorizzata a procedere con le credenziali fornite
        '404':
          content:
            application/json; charset=utf-8:
              example:
                code: 12345678
                errorDescription: hello
                errorURI: null
                expectedType: null
                field: null
                requestID: null
                service: 12345678
                statusCode: 12345678
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: La richiesta fa riferimento ad una risorsa inesistente
        '417':
          content:
            application/json; charset=utf-8:
              example:
                code: 12345678
                errorDescription: hello
                errorURI: null
                expectedType: null
                field: null
                requestID: null
                service: 12345678
                statusCode: 12345678
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: La richiesta non è corretta semanticamente
      security:
      - ThirdPartyClientCredential:
        - account:read
      - ThirdPartyAuthorizationCode:
        - account:read
      summary: Ultimi dati disponibili
      tags:
      - Saldo
      operationId: getByTenantIDBalancesLast
      x-operation-id-source: derived
components:
  schemas:
    Balance:
      properties:
        balance:
          example: '123.45'
          format: double
          type: number
        balanceType:
          example: string
          type: string
        currency:
          example: EUR
          type: string
        date:
          example: '2020-03-03T17:32:28Z'
          format: date-time
          type: string
        iban:
          example: IT59Q0300203280162876621571
          type: string
      required:
      - iban
      - balance
      - date
      - currency
      - balanceType
      type: object
    LatestBalances:
      additionalProperties:
        additionalProperties:
          additionalProperties:
            $ref: '#/components/schemas/Balance'
          type: object
        type: object
      type: object
    ErrorDTO:
      description: "Formato errore standard\n    \nLista dei possibili codici di errore:\n\n| codice | descrizione |\n| ------ | ----------- |\n| 401 | Errore generale di codifica |\n| 402 | Campo necessario mancante |\n| 403 | Valore di un campo del tipo sbagliato |\n| 404 | Valore di un campo assente |\n| 405 | Errore di codifica sconosciuto |\n| 406 | Null pointer exception |\n| 407 | Campo necessario mancante |\n| 408 | Errore di connessione |\n| 409 | Errore di input output |\n| 410 - 428 | Errore generico con il database |\n| 429, 432, 433 | Errore di logica con il database |\n| 430 | Campo invalido |\n| 431 | Campo assente |\n| 434 | Risultati non trovati |\n| 500 | Errore generico |\n| 2000 | Tenant non specificato |\n| 2001 | Non autorizzato ad operare su questa risorsa |\n| 2002 | Impossibile eliminare il documento poiché sono presente dei pagamenti collegati |\n| 2003 | Non autorizzato a creare la risorsa |\n| 2004 | Non autorizzato ad operare su questa risorsa |\n| 2005 | Si sta provando a modificare un termine non di questo documento |\n| 2006 | Codice istant scaduto |\n| 2007 | Non autorizzato generare un codice instant |\n| 2008 | Codice instant inesistente o non autorizzato a leggerlo |\n| 2012 | Si sta provando a caricare un documento già esistente |\n| 3001 | Tenant non specificato |\n| 4001 | Tenant non specificato |\n| 5001 | Corpo richiesta mancante |\n| 5002 | Corpo richiesta non valido |\n| 5003 | Vatcode del ricevente fattura mancante |\n| 6001 | Tenant non specificato |\n| 6002 | Ricevuta non trovata |\n| 8005 | Non puoi modificare questo conto |\n| 8010 | Troppi risultati ottenuti |\n| 11001 | Non autorizzato ad accedere a questa risorsa |\n| 11002 | Si sta provando a caricare un documento già esistente |\n| 13001 | Azienda non trovata |\n| 13003 | vatcode non è valido |"
      properties:
        code:
          description: Codice errore
          example: '12345678'
          format: int64
          type: integer
        errorDescription:
          description: Descrizione errore
          example: string
          type: string
        errorURI:
          description: URI dell'errore se presente
          example: string
          type: string
        expectedType:
          description: Nel caso di un errore di codifica indica il tipo di dato che non si è riuscito a decodificare
          example: string
          type: string
        field:
          description: Nel caso di un errore di codifica indica il campo che non si è riuscito a decodificare
          example: string
          type: string
        requestID:
          description: ID della richiesta da comunicare per poter fornire un supporto
          example: string
          type: string
        service:
          description: ID interno del servizio
          example: '12345678'
          format: int64
          type: integer
        statusCode:
          description: Codice di stato HTTP
          example: '12345678'
          format: int64
          type: integer
      required:
      - service
      - code
      - errorDescription
      - statusCode
      type: object
    Balances:
      additionalProperties:
        additionalProperties:
          additionalProperties:
            items:
              $ref: '#/components/schemas/Balance'
            type: array
          type: object
        type: object
      type: object
  securitySchemes:
    ThirdPartyAuthorizationCode:
      description: Autorizzazione oauth ottenuta da terze parti con un authorization flow
      flows:
        authorizationCode:
          authorizationUrl: https://core.flowpay.it/api/openid/authenticate
          refreshUrl: https://core.flowpay.it/api/oauth/token
          scopes:
            account:read: Operazioni di lettura sui conti
            bill:write: Creazione e gestione di ricevute
            business:read: Operazioni di lettura sulle informazioni della azienda
            contacts:read: Operazioni di lettura sulla rete aziendale
            invoice:read: Operazioni di lettura sulle fatture
            invoice:write: Operazioni di scrittura sulle fatture
            payment:read: Operazioni di lettura sui pagamenti
            salary:read: Operazioni di lettura sulle buste paga
            salary:write: Operazioni di scrittura sui salary
            statistic:read: Lettura dei dati statistici raggruppati
            transfer:read: Operazioni di lettura sui trasferimenti
            transfer:write: Operazioni di scrittura sui trasferimenti
          tokenUrl: https://core.flowpay.it/api/oauth/token
      type: oauth2
    ThirdPartyClientCredential:
      description: Autorizzazione oauth ottenuta da terze parti con client credential flow
      flows:
        clientCredentials:
          refreshUrl: https://core.flowpay.it/api/oauth/token
          scopes:
            account:read: Operazioni di lettura sui conti
            account:write: Operazione di modifica sui conti
            authorization_intent: Creazione di intenti a consensi relativi a risorse di un utente
            bill: Gestione di ricevute
            business:read: Operazioni di lettura sulle informazioni della azienda
            invoice:read: Operazioni di lettura sulle fatture
            invoice:write: Operazioni di scrittura sulle fatture
            pagopa: ''
            payment:read: Operazioni di lettura sui pagamenti
            salary:read: Operazioni di lettura sulle buste paga
            salary:write: Operazioni di scrittura sui salary
            statistic:read: Lettura dei dati statistici raggruppati
            transfer:read: ''
            transfer:write: ''
          tokenUrl: https://core.flowpay.it/api/oauth/token
      type: oauth2
